load("@otp//buck2/constraints:defs.bzl", "transition_force_constraints", "transition_ignore_constraints")
load("@otp//buck2:erlang.bzl", "erlang_bootstrap_app", "erts_release", "erlang_otp_release")

# bootstrap-0 uses pre-built versions of kernel, stdlib and compiler
erlang_otp_release(
    name = "bootstrap-0",
    erts = ":erts-mini",
    boots = [
        "bin/start.boot",
        "bin/no_dot_erlang.boot",
    ],
    apps = [
        ":prebuilt_kernel",
        ":prebuilt_stdlib",
        ":prebuilt_compiler",
    ],
    bootstrapping = True,
    incoming_transition = ":no-erlang-toolchain",
    visibility = ["PUBLIC"],
)

# bootstrap-1 extends bootstrap-0 with asn1, parsetools and sasl,
erlang_otp_release(
    name = "bootstrap-1",
    erts = ":erts-mini",
    boots = [
        "bin/start.boot",
        "bin/no_dot_erlang.boot",
    ],
    extends = ":bootstrap-0",
    apps = [
        # Needed by public-key
        "otp//lib/asn1:app",

        # Needed by anything with an yrl
        "otp//lib/parsetools:app",

        # Needed to create start.boot
        "otp//lib/sasl:app",
    ],
    bootstrapping = True,
    incoming_transition = ":use-bootstrap-0",
    visibility = ["PUBLIC"],
)

# bootstrap-2 is a minimal devel toolchain, built with bootstrap-1
erlang_otp_release(
    name = "bootstrap-2",
    erts = ":erts-devel",
    boots = [
        "bin/start.boot",
        "bin/no_dot_erlang.boot",
    ],
    extends = ":bootstrap-1",
    apps = [
        "otp//lib/kernel:app",
        "otp//lib/stdlib:app",
        "otp//lib/compiler:app",

        # Needed by buck2's dependency-analyszer and diameter
        "otp//lib/syntax_tools:app",

        # Needed by ssh
        "otp//lib/public_key:app",

        # Needed for common-test
        "otp//lib/xmerl:app",

        # To run tests
        "otp//lib/common_test:app",
    ],
    bootstrapping = True,
    incoming_transition = ":use-bootstrap-1",
    visibility = ["PUBLIC"],
)

erts_release(
    name = "erts-mini",
    erl = "otp//erts/etc:dyn_erl",
    beam = "otp//erts/emulator:beam",
    bins = [
        "otp//erts/etc:erlc",
        "otp//erts/etc:escript",
    ],
    internal_bins = [
        "otp//erts/etc:erlexec",
        "otp//erts/etc:inet_gethost",
        "otp//erts/emulator:erl_child_setup",
    ],
)

erts_release(
    name = "erts-devel",
    erl = "otp//erts/etc:dyn_erl",
    beam = "otp//erts/emulator:beam",
    bins = [
        "otp//erts/etc:erlc",
        "otp//erts/etc:escript",
        "otp//erts/epmd:epmd",
    ],
    internal_bins = [
        "otp//erts/etc:erlexec",
        "otp//erts/etc:inet_gethost",
        "otp//erts/emulator:erl_child_setup",
    ],
)

erlang_bootstrap_app(
    name = "prebuilt_kernel",
    app_name = "kernel",
    beams = glob(["lib/kernel/ebin/*.beam"]),
    include = glob(["lib/kernel/include/*.hrl"]),
    app_file = "lib/kernel/ebin/kernel.app",
)

erlang_bootstrap_app(
    name = "prebuilt_stdlib",
    app_name = "stdlib",
    beams = glob(["lib/stdlib/ebin/*.beam"]),
    include = glob(["lib/stdlib/include/*.hrl"]),
    app_file = "lib/stdlib/ebin/stdlib.app",
)

erlang_bootstrap_app(
    name = "prebuilt_compiler",
    app_name = "compiler",
    beams = glob(["lib/compiler/ebin/*.beam"]),
    include = glob(["lib/compiler/include/*.hrl"]),
    app_file = "lib/compiler/ebin/compiler.app",
)

transition_ignore_constraints(
    name = "no-erlang-toolchain",
    constraints = ["otp//buck2/constraints/erlang_toolchain:erlang_toolchain"],
)

transition_force_constraints(
    name = "use-bootstrap-0",
    constraints = ["otp//buck2/constraints/erlang_toolchain:bootstrap-0"],
)

transition_force_constraints(
    name = "use-bootstrap-1",
    constraints = ["otp//buck2/constraints/erlang_toolchain:bootstrap-1"],
)

transition_force_constraints(
    name = "use-bootstrap-2",
    constraints = ["otp//buck2/constraints/erlang_toolchain:bootstrap-2"],
    visibility = ["PUBLIC"],
)
