load(
    "defs.bzl",
    "system_erlang_toolchain",
    "local_erlang_toolchain",
    "erlang_toolchain_utilities_override",
)

local_erlang_toolchain(
    name = "bootstrap-0",
    otp_release = "otp//bootstrap:bootstrap-0",
    toolchain_utilities = "toolchains//erlang:erlang-bootstrap-utils",
)

system_erlang_toolchain(
    name = "system",
)

erlang_toolchain_utilities_override(
    name = "erlang-bootstrap-utils",
    dependency_analyzer = "bootstrap_dependency_analyzer.erl",
)
