load(
    "defs.bzl",
    "system_erlang_toolchain",
    "local_erlang_toolchain",
    "erlang_toolchain_utilities_override",
)

local_erlang_toolchain(
    name = "bootstrap-0",
    otp_release = "otp//bootstrap:bootstrap-0",
    toolchain_utilities = "toolchains//erlang:erlang-bootstrap-utils",
)

local_erlang_toolchain(
    name = "bootstrap-1",
    otp_release = "otp//bootstrap:bootstrap-1",
    toolchain_utilities = "toolchains//erlang:erlang-bootstrap-utils",
)

local_erlang_toolchain(
    name = "bootstrap-2",
    otp_release = "otp//bootstrap:bootstrap-2",
    toolchain_utilities = "toolchains//erlang:erlang-utils",
)

local_erlang_toolchain(
    name = "otp-devel",
    otp_release = "otp//:otp-devel",
    toolchain_utilities = "toolchains//erlang:erlang-utils",
)

local_erlang_toolchain(
    name = "compiler-testing",
    otp_release = "otp//lib/compiler/test:testing-toolchain",
    toolchain_utilities = "toolchains//erlang:erlang-utils",
)

system_erlang_toolchain(
    name = "system",
    toolchain_utilities = "toolchains//erlang:erlang-utils",
)

erlang_toolchain_utilities_override(
    name = "erlang-bootstrap-utils",
    app_src_script = "otp_app_src_builder.erl",
    dependency_analyzer = "bootstrap_dependency_analyzer.erl",
)

erlang_toolchain_utilities_override(
    name = "erlang-utils",
    app_src_script = "otp_app_src_builder.erl",
)
