load("@otp//buck2/constants.bzl", "PARSETOOLS_VSN")

erlang_application(
    name = "app",
    app_name = "parsetools",
    app_src = "src/parsetools.app.src",
    version = PARSETOOLS_VSN,

    srcs = glob(["src/*.erl", "src/*.hrl"]) + [
        "otp//lib/stdlib:include/erl_compile.hrl",
        "otp//lib/stdlib:include/ms_transform.hrl",
    ],

    includes = glob(["include/*.hrl"]),

    applications = [
        "kernel",
        "stdlib",
    ],

    erl_opts = [
        "-Werror",
    ],

    # During bootstrapping, we wan't to compile as little Erlang code
    # as possible, in particular, we need to avoid the buck2 support modules used
    # for the shell.
    shell_libs = select({
        "otp//buck2/constraints/erlang_toolchain:bootstrap-0": [],
        "DEFAULT": None,
    }),

    visibility = ["PUBLIC"],
)
