load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("@prelude//toolchains:zip_file.bzl", "zip_file_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("erlang.bzl", "system_erlang_toolchain")
load("cxx.bzl", "cxx_tools_info", "c_flags", "cxx_flags", "link_flags")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    c_flags = c_flags(),
    cxx_flags = cxx_flags(),
    link_flags = link_flags(),
    visibility = ["PUBLIC"],
    _cxx_tools_info = cxx_tools_info(),
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_erlang_toolchain(
    name = "erlang-system",
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

zip_file_toolchain(
    name = "zip_file",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "erlang-default",
    actual = ":erlang-system",
    visibility=["PUBLIC"],
)
