load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("@prelude//toolchains:zip_file.bzl", "zip_file_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("cxx.bzl", "cxx_tools_info", "c_flags", "cxx_flags", "link_flags")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    c_flags = c_flags(),
    cxx_flags = cxx_flags(),
    link_flags = link_flags(),
    visibility = ["PUBLIC"],
    _cxx_tools_info = cxx_tools_info(),
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)

zip_file_toolchain(
    name = "zip_file",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "erlang-default",
    actual = select({
        "otp//buck2/constraints/erlang_toolchain:bootstrap-0": "toolchains//erlang:bootstrap-0",
        "otp//buck2/constraints/erlang_toolchain:bootstrap-1": "toolchains//erlang:bootstrap-1",
        "otp//buck2/constraints/erlang_toolchain:system": "toolchains//erlang:system",
    }),
    visibility=["PUBLIC"],
)
