load("@otp//buck2/constants.bzl", "KERNEL_VSN")
load("@toolchains//erlang:defs.bzl", "COMMON_ERL_OPTS")

erlang_application(
    name = "app",
    app_name = "kernel",
    app_src = "src/kernel.app.src",
    version = KERNEL_VSN,

    srcs = glob(
        ["src/*.erl", "src/*.hrl"],
        exclude = ["src/inet_dns_record_adts.hrl"],
    ) + [
        ":inet_dns_record_adts.hrl",
    ],

    includes = glob(["include/*.hrl"]),

    erl_opts = COMMON_ERL_OPTS + [
        "-Werror",
        "+warn_deprecated_catch",
    ],

    visibility = ["PUBLIC"],
)

[
    export_file(
        name = hrl,
        visibility = ["otp//lib/stdlib:app"],
    )
    for hrl in ["include/logger.hrl", "include/file.hrl"]
]

genrule(
    name = "inet_dns_record_adts.hrl",
    cmd = "perl ${SRCS} > ${OUT}",
    env = {"LANG": "C"},
    srcs = ["src/inet_dns_record_adts.pl"],
    out = "inet_dns_record_adts.hrl",
)

export_file(
    name = "include/inet.hrl",
    visibility = ["otp//lib/common_test:app"],
)

export_file(
    name = "src/logger_internal.hrl",
    visibility = ["otp//lib/common_test:app"],
)
