load("@otp//buck2/autotools:defs.bzl", "configure")
load("@otp//buck2/cxx.bzl", "strip_include_prefix")

configure(
    name = "config",
    script = "configure",
    srcs = [
        "config.h.in",
        "include/erl_int_sizes_config.h.in",
        "include/internal/ethread_header_config.h.in",
    ],
)

cxx_library(
    name = "headers",
    exported_headers = (
        {
            "config.h": ":config[config.h]",
            "erl_int_sizes_config.h": ":config[include/erl_int_sizes_config.h]",
            "ethread_header_config.h": ":config[include/internal/ethread_header_config.h]",
        } |
        strip_include_prefix(
            "include/internal/",
            glob([
                "include/internal/*.h",
                "include/internal/gcc/*.h",
                "include/internal/i386/*.h",
                "include/internal/libatomic_ops/*.h",
                "include/internal/ppc32/*.h",
                "include/internal/pthread/*.h",
                "include/internal/tile/*.h",
                "include/internal/win/*.h",
                "include/internal/x86_64/*.h",
            ])
        )
    ),
    header_namespace = "",
    visibility = ["PUBLIC"],
    link_style = "static",
)

cxx_library(
    name = "common",
    srcs = glob(["lib_src/common/*.c"]) + select({
        "config//os:windows": glob(["lib_src/win/*.c"]),
        "DEFAULT": glob(["lib_src/pthread/*.c"]),
    }),
    exported_deps = [":headers"],
    visibility = ["PUBLIC"],
)
