load("@otp//buck2/constants.bzl", "EPMD_PORT_NO")
load("@otp//buck2/tests:defs.bzl", "otp_tests")

cxx_binary(
    name = "epmd",
    srcs = glob(["src/*.c"]),
    headers = glob(["src/*.h"]),
    deps = [
        "otp//erts:common",
    ],
    compiler_flags = [
        "-DEPMD_PORT_NO={}".format(EPMD_PORT_NO)
    ],
    visibility = ["PUBLIC"],
)

otp_tests(
    name = "tests",
    suites = glob(["test/*_SUITE.erl"]),
    resources = [
        ":epmd",
    ]
)
