cxx_library(
    name = "lib",
    srcs = glob(["*.c"]),
    headers = glob(["*.h"]),
    exported_headers = ["ryu.h"],
    header_namespace = "",
    link_style = "static",
    visibility = ["PUBLIC"],
)
