load(
    "@otp//buck2/codegen:defs.bzl",
    "alloc_types",
    "beam_asm_global",
    "build_flags",
    "beam_opcodes",
    "driver_tab",
    "preloaded",
    "tables",
    "yielding_c_fun",
)
load(
    "@otp//buck2:cxx.bzl",
    "ASMJIT_FLAGS",
    "flatten_includes",
    "headers_union",
    "strip_include_prefix",
)
load(
    "@toolchains//:cxx.bzl",
    "c_flags",
    "link_flags",
)


alloc_types(
    name = "alloc_types",
    src = "beam/erl_alloc.types",
)

beam_opcodes(
    name = "opcodes-emu",
    small_code_model = False,
    srcs = [
        "otp//lib/compiler:src/genop.tab",
        "beam/predicates.tab",
        "beam/generators.tab",
        "beam/emu/ops.tab",
        "beam/emu/predicates.tab",
        "beam/emu/generators.tab",
        "beam/emu/macros.tab",
        "beam/emu/instrs.tab",
        "beam/emu/arith_instrs.tab",
        "beam/emu/bif_instrs.tab",
        "beam/emu/bs_instrs.tab",
        "beam/emu/float_instrs.tab",
        "beam/emu/map_instrs.tab",
        "beam/emu/msg_instrs.tab",
        "beam/emu/select_instrs.tab",
        "beam/emu/trace_instrs.tab",
    ],
    compatible_with = [
        "otp//buck2/constraints/emu_flavor:emu"
    ],
)

beam_opcodes(
    name = "opcodes-jit",
    small_code_model = False,
    srcs = [
        "otp//lib/compiler:src/genop.tab",
        "beam/predicates.tab",
        "beam/generators.tab",
    ] + select({
        "@otp//buck2/config/emu_flavor:jit-x86_64": [
            "beam/jit/x86/ops.tab",
            "beam/jit/x86/predicates.tab",
            "beam/jit/x86/generators.tab",
        ],
        "@otp//buck2/config/emu_flavor:jit-aarch64": [
            "beam/jit/arm/ops.tab",
            "beam/jit/arm/predicates.tab",
            "beam/jit/arm/generators.tab",
        ],
    }),
    compatible_with = [
        "otp//buck2/constraints/emu_flavor:jit"
    ],
)

tables(
    name = "tables",
    atoms = "beam/atom.names",
    bifs = "beam/bif.tab",
    dirty_bifs = "beam/erl_dirty_bif.tab",
)

preloaded(
    name = "preload.c",
    srcs = "otp//erts/preloaded:ebin",
)

yielding_c_fun(
    name = "erl_db_insert_list.ycf.h",
    src = "beam/erl_db.c",
    args = [
        "-yield",
        "-static_aux_funs",
        "-only_yielding_funs",
        "-f", "ets_insert_2_list_check",
        "-f", "ets_insert_new_2_list_has_member",
        "-f", "ets_insert_2_list_from_p_heap",
        "-f", "ets_insert_2_list_destroy_copied_dbterms",
        "-f", "ets_insert_2_list_copy_term_list",
        "-f", "ets_insert_new_2_dbterm_list_has_member",
        "-f", "ets_insert_2_list_insert_db_term_list",
        "-f", "ets_insert_2_list",
        "-fnoauto", "ets_insert_2_list_lock_tbl",
    ],
)

yielding_c_fun(
    name = "erl_map.ycf.h",
    src = "beam/erl_map.c",
    args = [
        "-yield",
        "-static_aux_funs",
        "-only_yielding_funs",
        "-fnoauto", "maps_keys_1_helper",
        "-fnoauto", "maps_values_1_helper",
        "-fnoauto", "maps_from_keys_2_helper",
        "-fnoauto", "maps_from_list_1_helper",
        "-fnoauto", "hashmap_from_validated_list",
        "-f", "hashmap_keys",
        "-f", "hashmap_values",
        "-f", "hashmap_from_unsorted_array",
        "-f", "hashmap_from_sorted_unique_array",
        "-f", "hashmap_from_chunked_array",
        "-fexternal", "erts_qsort",
    ],
)

yielding_c_fun(
    name = "utils.ycf.h",
    src = "beam/utils.c",
    args = [
        "-yield",
        "-only_yielding_funs",
        "-f", "erts_qsort",
        "-f", "erts_qsort_helper",
        "-f", "erts_qsort_partion_array",
    ],
)

driver_tab(
    name = "driver_tab.c",
    nifs = glob(["nifs/common/*_nif.c"]),
    static_nifs = [
        "otp//lib/asn1:nif_files",
        "otp//lib/crypto:nif_files",
    ],
    drivers = glob(["drivers/common/*_drv.c"]),
)

cxx_library(
    name = "headers",
    exported_deps = [
        "otp//erts:headers",
        "otp//erts/emulator/openssl:headers",
    ],
    exported_headers = headers_union(
        flatten_includes(
            glob([
                "sys/common/*.h",
                "sys/unix/*.h",
                "beam/jit/beam_asm.h",
            ]),
        ),
        strip_include_prefix(
            "beam/",
            glob([
                "beam/*.h",
                "beam/jit/*.h",
            ])
        ),
        {
            "erl_alloc_types.h": ":alloc_types[erl_alloc_types.h]",
            "erl_atom_table.h": ":tables[erl_atom_table.h]",
            "erl_bif_table.h": ":tables[erl_bif_table.h]",
            "erl_version.h": "otp//erts:erl_version.h",

            "erl_db_insert_list.ycf.h": ":erl_db_insert_list.ycf.h",
            "erl_map.ycf.h": ":erl_map.ycf.h",
            "utils.ycf.h": ":utils.ycf.h",
        },
        select({
            "otp//buck2/config/emu_flavor:emu": {
                "beam_opcodes.h": ":opcodes-emu[beam_opcodes.h]",
                "beam_cold.h": ":opcodes-emu[beam_cold.h]",
                "beam_warm.h": ":opcodes-emu[beam_warm.h]",
                "beam_hot.h": ":opcodes-emu[beam_hot.h]",
            },

            "otp//buck2/config/emu_flavor:jit": {
                "beam_opcodes.h": ":opcodes-jit[beam_opcodes.h]",
                "beamasm_emit.h": ":opcodes-jit[beamasm_emit.h]",
                "beamasm_protos.h": ":opcodes-jit[beamasm_protos.h]",
            }
        })
    ),
    header_namespace = "",
    visibility = ["PUBLIC"],
)

cxx_binary(
    name = "erl_child_setup",
    srcs = [
        "beam/hash.c",
        "sys/unix/erl_child_setup.c",
        "sys/unix/sys_uds.c",
    ],
    deps = [
        ":headers"
    ],
    visibility = ["PUBLIC"],
)

genrule(
    name = "erl_poll.flbk.c",
    cmd = """
    echo '#define ERTS_NO_KERNEL_POLL_VERSION"' > $OUT
    cat $SRCS >> $OUT
    """,
    srcs = ["sys/common/erl_poll.c"],
    out = "erl_poll.flbk.c",
)

cxx_library(
    name = "sys",
    srcs = glob(["sys/common/*.c", "sys/unix/*.c"], exclude = [
        "sys/unix/erl_child_setup.c",
        "sys/unix/erl_main.c",
    ]) + [
        ":erl_poll.flbk.c",
    ],
    deps = [
        ":headers",
        "otp//erts:common",
    ],
    link_style = "static",
)

cxx_library(
    name = "emu",
    srcs = glob(["beam/emu/*.c"]) + [
        ":opcodes-emu[beam_opcodes.c]",
    ],
    headers = {
        "emu/load.h": "beam/emu/load.h",
    },
    header_namespace = "",
    deps = [
        ":headers",
        ":opcodes-emu",
    ],
    target_compatible_with = [
        "otp//buck2/config/emu_flavor:emu",
    ],
    modifiers = [
        "otp//buck2/config/emu_flavor:emu",
    ],
    link_style = "static",
)


beam_asm_global(
    name = "beam/jit/x86/beam_asm_global.hpp",
    src = "beam/jit/x86/beam_asm_global.hpp.pl",
)

beam_asm_global(
    name = "beam/jit/arm/beam_asm_global.hpp",
    src = "beam/jit/arm/beam_asm_global.hpp.pl",
)

cxx_library(
    name = "jit-x86",
    srcs = glob(["beam/jit/*.cpp", "beam/jit/x86/*.cpp"]),
    headers = headers_union(
        flatten_includes(glob([
            "beam/jit/*.h",
            "beam/jit/*.hpp",
            "beam/jit/x86/*.hpp"
        ])),
       {"beam_asm_global.hpp": ":beam/jit/x86/beam_asm_global.hpp"},
    ),
    header_namespace = "",
    deps = [
        ":headers",
        "@otp//erts/emulator/asmjit:lib",
    ],
    precompiled_header = "@otp//erts/emulator/asmjit:pch",
    compiler_flags = ASMJIT_FLAGS,
    target_compatible_with = [
        "config//cpu:x86_64",
        "otp//buck2/constraints/emu_flavor:jit",
    ],
    modifiers = [
        "otp//buck2/constraints/emu_flavor:jit",
    ],
    link_style = "static",
)

cxx_library(
    name = "jit-arm",
    srcs = glob(["beam/jit/*.cpp", "beam/jit/arm/*.cpp"]),
    headers = headers_union(
        flatten_includes(glob([
            "beam/jit/*.h",
            "beam/jit/*.hpp",
            "beam/jit/arm/*.hpp"
        ])),
       {"beam_asm_global.hpp": ":beam/jit/arm/beam_asm_global.hpp"},
    ),
    header_namespace = "",
    deps = [
        ":headers",
        "@otp//erts/emulator/asmjit:headers-arm",
        "@otp//erts/emulator/asmjit:lib",
    ],
    precompiled_header = "@otp//erts/emulator/asmjit:pch",
    compiler_flags = ASMJIT_FLAGS,
    target_compatible_with = [
        "config//cpu:arm64",
        "otp//buck2/constraints/emu_flavor:jit"
    ],
    modifiers = [
        "otp//buck2/constraints/emu_flavor:jit"
    ],
    link_style = "static",
)

cxx_library(
    name = "jit",
    srcs = glob(["beam/jit/*.c"]) + [
        ":opcodes-jit[beam_opcodes.c]",
    ],
    deps = [
        ":headers",
    ],
    exported_deps =  select({
        "otp//buck2/config/emu_flavor:jit-x86_64": [":jit-x86"],
        "otp//buck2/config/emu_flavor:jit-aarch64": [":jit-arm"],
    }),
    target_compatible_with = [
        "otp//buck2/config/emu_flavor:jit"
    ],
    link_style = "static",
)

build_flags(
    name = "erl_compile_flags.h",
    srcs = {
        "CONFIG_H": "otp//erts:config.h",
        "CFLAGS": c_flags(),
        "LDFLAGS": link_flags(),
    },
)

cxx_library(
    name = "nifs",
    srcs = glob(["nifs/common/*.c", "nifs/unix/*.c"]),
    headers = flatten_includes(
        glob(["nifs/common/*.h", "nifs/unix/*.h"]),
    ),
    header_namespace = "",
    deps = [
        ":headers",
        "otp//erts/emulator/zstd:lib",
    ],
    link_style = "static",
)

cxx_library(
    name = "beam-lib",
    srcs = glob([
        "beam/*.c",
        "drivers/common/*.c",
    ]) + [
        ":tables[erl_atom_table.c]",
        ":tables[erl_bif_table.c]",
        ":tables[erl_dirty_bif_wrap.c]",
        ":tables[erl_guard_bifs.c]",
        ":driver_tab.c",
        ":preload.c",
    ],
    headers = [
        ":erl_compile_flags.h",
    ],
    header_namespace = "",
    deps = [":headers"],
    exported_deps = [
        ":nifs",
        ":sys",
        "otp//erts:common",
        "otp//erts/emulator/openssl:lib",
        "otp//erts/emulator/pcre:lib",
        "otp//erts/emulator/ryu:lib",
        "otp//erts/emulator/zlib:lib",
        "otp//lib/asn1:nif",
        "otp//lib/crypto:nif",
    ] + select({
        "otp//buck2/config/emu_flavor:emu": [":emu"],
        "otp//buck2/config/emu_flavor:jit": [":jit"],
    }),
    link_style = "static",
)
