load("@otp//buck2/constants.bzl", "CRYPTO_VSN")
load("@otp//buck2:cxx.bzl", "flatten_includes")
load("@toolchains//erlang:defs.bzl", "COMMON_ERL_OPTS")

erlang_application(
    name = "app",
    app_name = "crypto",
    app_src = "src/crypto.app.src",
    version = CRYPTO_VSN,

    srcs = glob(["src/*.erl"]),

    applications = [
        "kernel",
        "stdlib",
    ],

    erl_opts = COMMON_ERL_OPTS + [
        "-DCRYPTO_VSN={}".format(repr(CRYPTO_VSN)),
        "-Werror",
    ],

    visibility = ["PUBLIC"],
)

filegroup(
    name = "nif_files",
    srcs = ["c_src/crypto.c"],
    visibility = ["PUBLIC"],
)

cxx_library(
    name = "nif",
    srcs = glob(["c_src/**/*.c"]),
    headers = flatten_includes(glob(["c_src/**/*.h"])),
    header_namespace = "",
    deps = ["otp//erts/emulator:headers"],
    compiler_flags = [
        "-DSTATIC_ERLANG_NIF",
        "-DDISABLE_EVP_DH=0",
        "-DDISABLE_EVP_HMAC=0",
    ],
    link_style = "static",
    visibility = ["PUBLIC"],
)
